import { Geist, Geist_Mono } from "next/font/google";
import connectToDatabase from '../../utils/mongodb';
import User from '../app/models/User';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
await connectToDatabase();

  console.log(' User model loaded successfully:', !!User);

  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  );
}
