// app/layout.js
import { Geist, Geist_Mono } from "next/font/google";
import connectToDatabase from '../../utils/mongodb';
import "./globals.css";
import Providers from "../components/Providers";
import { Toaster } from 'react-hot-toast'; // <-- import Toaster

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await connectToDatabase();

  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
          <Toaster position="top-right" />  {/* <-- mount Toaster */}
        </Providers>
      </body>
    </html>
  );
}
